FROM --platform=$BUILDPLATFORM python:3.9
ARG BLUE_BUILD_CACHE_ARG
ARG BLUE_BUILD_LIB_ARG

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.txt /app/requirements.txt
RUN pip install --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.txt

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "websocket_counter_service.py" ] 
