FROM python:3.9

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.core /app/requirements.core
RUN pip install --no-cache --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.core

ADD src/requirements.agent /app/requirements.agent
RUN pip install --no-cache -r requirements.agent

ADD src/requirements.template_interactive /app/requirements.template_interactive
RUN pip install --no-cache -r requirements.template_interactive

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "template_interactive_agent.py"]
