FROM --platform=$BUILDPLATFORM python:3.10.12
ARG BLUE_BUILD_CACHE_ARG
ARG BLUE_BUILD_LIB_ARG

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.core /app/requirements.core
RUN pip install ${BLUE_BUILD_CACHE_ARG} ${BLUE_BUILD_LIB_ARG} -r requirements.core

ADD src/requirements.agent /app/requirements.agent
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.agent

ADD src/requirements.registry /app/requirements.registry
RUN pip install --no-cache-dir --no-cache --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.registry

ADD src/requirements.requestor /app/requirements.requestor
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.requestor

ADD src/requirements.tool /app/requirements.tool
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.tool

ADD src/requirements.dialogue_manager /app/requirements.dialogue_manager
RUN pip install ${BLUE_BUILD_CACHE_ARG} -r requirements.dialogue_manager

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "dialogue_manager.py"]
