FROM python:3.9

# Set workdir
WORKDIR /app

# Build requirements first
ADD src/requirements.core /app/requirements.core
RUN pip install --no-cache --extra-index-url  http://10.0.160.75:8888/simple/ --trusted-host 10.0.160.75 -r requirements.core

ADD src/requirements.agent /app/requirements.agent
RUN pip install --no-cache -r requirements.agent

ADD src/requirements.basic_planner /app/requirements.basic_planner
RUN pip install --no-cache -r requirements.basic_planner

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "basic_planner_agent.py"]
