from pydantic import BaseModel, field_validator, model_validator
from typing import List, Tuple
from collections import defaultdict, deque
import copy

class NodeValidator(BaseModel):
    index: str
    name: str
    instruction: str

    @field_validator("index", mode="before")
    @classmethod
    def normalize_index(cls, v):
        # Cast int -> str(int)
        return str(int(v))


class PlanValidator(BaseModel):
    nodes: List[NodeValidator]
    edges: List[Tuple[str, str]]

    @field_validator("edges", mode="before")
    @classmethod
    def normalize_edges(cls, edges):
        """
        Accept edges as list/tuple of ints or strings,
        cast them into tuple of str(int).
        """
        normalized = []
        for edge in edges:
            if not isinstance(edge, (list, tuple)) or len(edge) != 2:
                raise ValueError(f"Invalid edge format: {edge}")
            src, dst = edge
            normalized.append((str(int(src)), str(int(dst))))
        return normalized

    @model_validator(mode="after")
    def validate_nodes_and_edges(self):
        node_ids = {n.index for n in self.nodes}
        for src, dst in self.edges:
            if src not in node_ids:
                raise ValueError(f"Edge references missing node {src}")
            if dst not in node_ids:
                raise ValueError(f"Edge references missing node {dst}")
        return self

        
class LLMPlan:
    """
    Takes a json plan, potentially generated by LLM,
    validate plan format and prepare for convertion for Blue plan
    """
    def __init__(self, plan):
        # Validate & normalize input
        validated = PlanValidator(**plan)
        self.plan = validated.model_dump()

        # Ensure exactly one sink
        self.plan, self.sink_id = self._ensure_single_sink(self.plan)

        # Build adjacency
        self.nodes = {str(n["index"]): n for n in self.plan["nodes"]}
        self.adj_out = defaultdict(set)
        self.adj_in = defaultdict(set)

        for src, dst in self.plan["edges"]:
            self.adj_out[src].add(dst)
            self.adj_in[dst].add(src)
            if dst not in self.adj_out:
                self.adj_out[dst] = set()
            if src not in self.adj_in:
                self.adj_in[src] = set()

        # Check DAG validity
        if not self._is_dag():
            raise ValueError("Plan graph is not a valid DAG.")

    #####################
    ### LLM plan processing
    ####
    def _is_dag(self) -> bool:
        """Check DAG validity with Kahn’s algorithm."""
        indegree = {n: len(self.adj_in[n]) for n in self.nodes}
        q = deque([n for n, deg in indegree.items() if deg == 0])
        visited = 0
        while q:
            u = q.popleft()
            visited += 1
            for v in self.adj_out[u]:
                indegree[v] -= 1
                if indegree[v] == 0:
                    q.append(v)
        return visited == len(self.nodes)

    def _ensure_single_sink(self, plan):
        """Ensure DAG has exactly one sink node, add dummy if needed."""
        plan = copy.deepcopy(plan)
        nodes = plan["nodes"]
        edges = plan["edges"]

        node_ids = {str(n["index"]) for n in nodes}
        outgoing = defaultdict(set)
        for src, dst in edges:
            outgoing[src].add(dst)
            if dst not in outgoing:
                outgoing[dst] = set()

        sinks = [n for n in node_ids if not outgoing[n]]

        if len(sinks) == 0:
            raise ValueError("Plan graph is not a valid DAG.")
        if len(sinks) == 1:
            return plan, sinks[0]

        # Add dummy sink
        max_index = max(map(int, node_ids))
        dummy_id = str(max_index + 1)
        dummy_node = {
            "index": max_index + 1,
            "name": "Final Result",
            "instruction": "Collect the final output."
        }
        nodes.append(dummy_node)

        for s in sinks:
            edges.append((s, dummy_id))

        return plan, dummy_id

    # === Convenience methods ===
    def get_nodes(self) -> dict:
        return self.nodes

    def get_incoming(self, index: str) -> List[str]:
        return list(self.adj_in[str(index)])

    def get_sink(self) -> str:
        return self.sink_id
    