FROM --platform=$BUILDPLATFORM python:3.10.12-slim
ARG BLUE_BUILD_CACHE_ARG
ARG BLUE_BUILD_LIB_ARG
ARG BLUE_DEPLOY_VERSION
ENV BLUE_DEPLOY_VERSION=${BLUE_DEPLOY_VERSION}

# Set workdir
WORKDIR /app

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends iputils-ping \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip first
RUN pip install --no-cache-dir --upgrade pip

# Copy requirements first to leverage Docker layer caching
COPY src/requirements.* /app/

# Build requirements first
RUN pip install --no-cache-dir \
        -r requirements.agent \
        -r requirements.data \
        --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.registry \
        -r requirements.requestor \
        -r requirements.tool \
        -r requirements.openai \
        ${BLUE_BUILD_CACHE_ARG} ${BLUE_BUILD_LIB_ARG} -r requirements.core

# Copy service files
ADD /src /app/

ENTRYPOINT ["python", "dish_ideation_agent.py"]